# -*- coding: utf-8 -*-
"""Heart-Agile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZbgMtRtf8vWVhOSuUYyOlNlFEwFfJy-E

## HEART
"""

df = pd.read_csv("/content/heart.csv")
df.head()

"""### NAIVE BAYES"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

x=df.drop('target',axis=1)
y=df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

model = GaussianNB()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print(y_pred)

result_nb = accuracy_score(y_test, y_pred)
print("Accuracy:", result_nb * 100, "%")

"""### DECISION TREE"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

x=df.drop('target',axis=1)
y=df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

model = DecisionTreeClassifier(random_state=42)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print(y_pred)

result_dt = accuracy_score(y_test, y_pred)
print("Accuracy:", result_dt * 100, "%")

"""### SVM"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

x=df.drop('target',axis=1)
y=df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

model = SVC(kernel='linear')
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print(y_pred)

result_svm = accuracy_score(y_test, y_pred)
print("Accuracy:", result_svm * 100, "%")

"""### KNN"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

x=df.drop('target',axis=1)
y=df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.19,random_state=42)

k=3
model = KNeighborsClassifier(n_neighbors=k)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print(y_pred)

result_knn = accuracy_score(y_test, y_pred)
print("Accuracy:", result_knn * 100, "%")

"""### RANDOM FOREST"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

x=df.drop('target',axis=1)
y=df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.19,random_state=42)

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print(y_pred)

result_rf = accuracy_score(y_test, y_pred)
print("Accuracy:", result_rf * 100, "%")

"""### LOGISTIC REGRESSION"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

x=df.drop('target',axis=1)
y=df['target']

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

model = LogisticRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print(y_pred)

result_lr = accuracy_score(y_test, y_pred)
print("Accuracy:", result_lr * 100, "%")

"""### GRAPH"""

import matplotlib.pyplot as plt

accuracy_nb = 81.49
accuracy_dt = 97.07
accuracy_knn = 80.84
accuracy_svm = 89.74
accuracy_rf = 98.46
accuracy_lr = 78.53

models = ['Naïve Bayes', 'Decision Tree', 'KNN', 'SVM', 'Random Forest', 'Logistic Regression']
accuracies = [accuracy_nb, accuracy_dt, accuracy_knn, accuracy_svm, accuracy_rf, accuracy_lr]

# Plotting the accuracies as a line plot
plt.figure(figsize=(10, 6))
plt.plot(models, accuracies, marker='o', color='b', linestyle='-', markersize=8)
plt.xlabel('Models')
plt.ylabel('Accuracy (%)')
plt.title('Model Accuracy Comparison')
plt.ylim(75, 100)  # Adjust y-axis range to include all values
plt.yticks(range(75, 101, 5))  # Set y-axis ticks at intervals of 5
plt.grid(True)

plt.show()